---
title: "Module 3b: Economic damages associated with health impacts"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Module3b_health_eco}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Description

The functions in this module estimate economic impacts associated with the adverse health effects attributable to ambient air pollution. 

ADD TEXT (XXX methods)

### Values of Statistical Life (VSL)
Economic damages associated to the health impacts are calculated multiplying either the premature mortalities or the years of life lost by the corresponding Value of Statistical Life (VSL) or Value of Statistical Life Year (VSLY). Both the VSL and the VSLY are based on the widely accepted OECD values for 2005. According to the literature, this value ranges between US$1.8 and $4.5 million for VSL. The calculations for all regions are based on the  “unit value transfer approach” which adjusts the VSL according to their GDP and GDP growth rates, as detialed in [Narain and Sall 2016](https://openknowledge.worldbank.org/handle/10986/24440). In this version, we assume the income elasticity of both the VSL and the VSLY are equal to 0.8, with no adjustments across regions. A potential regional adjustment of these income elasticities will be explored in further developments of the package. We note that the central OECD values could be adjusted by the user. Finally, the damages reported by the functions use the median values of VSL and VSLY for simplicity. The reporting of Lower and Upper Bounds can be selected by the user, but requires some code changes. The systematic reporting of LB and UB is planned for the next package development.

### Method 2

### Method 3

## Example for the estimation of economic impacts

The following code shows some examples for the monetized premature deaths associated to exposure to PM2.5 and monetized years of life lost attributable to O3 exposure:

```{r setup_ecoloss, eval = F}
library(rfasst)
library(magrittr)

 db_path<-"path_to_your_gcam_database"
 query_path<-"path_to_your_gcam_queries_file"
 db_name<-"name of the database"
 prj_name<-" Name for a Project to add extracted results to" # (any name should work, avoid spaces just in case) 
 scen_name<-"Name of the GCAM scenario"
 queries<-"Name of the query file" # (the package includes a default query file that includes all the queries required in every function in the packae, "queries_rfasst.xml")

# ADD code

```















