name: test_coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        r: ['3.6']
        
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true      
      GITHUB_PAT: ${{ secrets.GH_PAT_RFASST}}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-tinytex@v2-branch
      - name: Cache R packages 
        uses: actions/cache@v1 
        with: 
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }} 
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1- 
      - name: Install dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          GITHUB_PAT: ${{ secrets.GH_PAT_RFASST }}
              - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck","covr", "rprojroot"), repos = "https://cloud.r-project.org")
          remotes::install_github("JGCRI/gcamdata")
          remotes::install_github("JGCRI/rpackageutils")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Test coverage
        run: |
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
